### ISSUE TITLE
What should we call individual items?

### ISSUE THREAD

**Issue by alecho** [UpstateRuby/openworks-status-api#5]
What should be the general term we use for items that we track? Things like HVAC, internet, water.

I was thinking "components".

@dmatthew4592 suggested "metrics"

**Comment by bgrange91** [comment]
I second using the term "components".

**Comment by simplyb** [comment]
How about resources?

**Comment by alecho** [comment]
I like "resources". My concern with "components" is that it's too general and largely meaningless. "resources" have many "metrics" makes sense to me as well.

**Comment by alecho** [comment]
Going to close this with the choice of "resources". We can reopen if anyone has a problem with a "ResourceResource" class name.
